POST http://localhost:8080/events/1/register
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFuaWthdGUxZGVAZ21haWwuY29tIiwiZXhwIjoxNzEyMzIzMDk5LCJpZCI6Mn0.yKTJdrhpg76QaNjIXwYw7GnGKfZRX-pVZyB3lJN5Sio